xlit: attention
xlit_conf:
    # Data Setting
    langx: ben
    langy: mni
    token_type: char
    db_file: db/transcribed.txt
    max_len: 100
    val_ratio: 0.25
    
    # Model Setting
    idim: 64
    odim: 47
    hidden_dim: 128
    embed_dim: 128
    elayers: 2
    dlayers: 2
    dropout: 0.25

    # Optimizer Setting
    optim: adam
    optim_conf:
        lr: 1.0e-03
        eps: 1.0e-06
        weight_decay: 0.0
    
    # Training Setting
    max_epoch: 50
    batch_size: 32
    keep_nbest_models: 5
    seed: 248
