xlit: transformer
xlit_conf:
    langx: ben
    langy: mni
    token_type: char
    db_file: db/transcribed.txt
    max_len: 100
    val_ratio: 0.25

    # Model
    idim: 64
    odim: 48
    embed_dim: 256
    num_heads: 4 
    num_encoder_layers: 4
    num_decoder_layers: 4 
    dim_feedforward: 512 
    dropout: 0.1

    # Optimizer
    optim: adam
    optim_conf:
        lr: 1.0e-4
        eps: 1.0e-6
        weight_decay: 0.0

    # Training
    max_epoch: 20
    batch_size: 16
    keep_nbest_models: 5
    seed: 248
